name: hwasi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.13
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  flutter_local_notifications: ^17.1.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  timezone: ^0.9.3
  smooth_page_indicator: ^1.2.1
  firebase_core: ^3.6.0
  
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.3
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/