// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvldDPwenjWXnX5GK8YMIeqthlSzPXBI',
    appId: '1:165507639857:android:b11f32e783bfe6fd6bc310',
    messagingSenderId: '165507639857',
    projectId: 'hwasi-ceafc',
    storageBucket: 'hwasi-ceafc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACL6LBAw4J7fdnfOkf8YkBeDtw9vc6Was',
    appId: '1:165507639857:ios:92d69819cfb29d016bc310',
    messagingSenderId: '165507639857',
    projectId: 'hwasi-ceafc',
    storageBucket: 'hwasi-ceafc.firebasestorage.app',
    iosBundleId: 'com.example.hwasiClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNB4Bur4FUDo7xFNnLK1yUXcnBMGjn50',
    appId: '1:165507639857:web:6dcc7b2efcb951a96bc310',
    messagingSenderId: '165507639857',
    projectId: 'hawsni-ceafc',
    authDomain: 'hawsni-ceafc.firebaseapp.com',
    storageBucket: 'hawsni-ceafc.firebasestorage.app',
    measurementId: 'G-L3WFP4EX6N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNB4Bur4FUDo7xFNnLK1yUXcnBMGjn50',
    appId: '1:165507639857:web:6dcc7b2efcb951a96bc310',
    messagingSenderId: '165507639857',
    projectId: 'hawsni-ceafc',
    authDomain: 'hawsni-ceafc.firebaseapp.com',
    storageBucket: 'hawsni-ceafc.firebasestorage.app',
    measurementId: 'G-L3WFP4EX6N',
  );
}
