import 'package:hwasi_app/core/services/api_service.dart';
import 'package:hwasi_app/features/address/data/models/address_model.dart';

class AddressService {
  Future<List<AddressModel>> getAddresses() async {
    try {
      final data = await ApiService.getAddresses();
      return data.map((e) => AddressModel.fromJson(e)).toList();
    } catch (e) {
      throw Exception('Failed to load addresses: $e');
    }
  }

  Future<AddressModel> addAddress(AddressModel address) async {
    try {
      final json = address.toJson();
      // Remove ID as it is generated by backend
      json.remove('id');
      json.remove('user_id');

      final data = await ApiService.addAddress(json);
      if (data == null) throw Exception('Failed to add address');
      return AddressModel.fromJson(data);
    } catch (e) {
      throw Exception('Failed to add address: $e');
    }
  }

  Future<AddressModel> updateAddress(AddressModel address) async {
    try {
      if (address.id == null)
        throw Exception('Address ID is required for update');

      final json = address.toJson();
      json.remove('id');
      json.remove('user_id');

      final data = await ApiService.updateAddress(address.id!, json);
      if (data == null) throw Exception('Failed to update address');
      return AddressModel.fromJson(data);
    } catch (e) {
      throw Exception('Failed to update address: $e');
    }
  }

  Future<void> deleteAddress(String addressId) async {
    try {
      final success = await ApiService.deleteAddress(addressId);
      if (!success) throw Exception('Failed to delete address');
    } catch (e) {
      throw Exception('Failed to delete address: $e');
    }
  }
}
